// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"pixi-filters","status":true,"description":"","parameters":{}},
{"name":"Lim_base_ui","status":true,"description":"UI核心","parameters":{}},
{"name":"vue.min","status":true,"description":"","parameters":{}},
{"name":"eventEdi","status":false,"description":"","parameters":{}},
{"name":"stellarisDossier","status":true,"description":"stellarisDossier","parameters":{}},
{"name":"stellarisEvent","status":true,"description":"stellarisEvent","parameters":{}}
];
